### ISSUE TITLE
MinimumLevel setting is ignored

### ISSUE THREAD

**Issue by feelgood-interface** [exceptionless/serilog-sinks-exceptionless#14]
Good day,
the Exceptionless Sink only send log messages with level _Warning_ or higher. Lower levels are ignored, due to `Exceptionless.Models.SettingsDictionary.GetMinLogLevel()` defaulting to _Warning_. Other sinks are working correctly. Downgrading to 3.1.0 seems to fix the problem.

Here is a similar issue: [https://github.com/exceptionless/Exceptionless.Net/issues/260](https://github.com/exceptionless/Exceptionless.Net/issues/260), but Constants.SourceContextPropertyName is being set on my side.

**Comment by niemyjski** [comment]
This is a duplicate; you'd need to call ExceptionlessClient.Default.Configuration.SetDefaultMinLogLevel with a default log level you want the client to send. Ideally, we'd maybe want to look at the serilog configuration and set the default min log level from that. If you want to take a stab at that in a pr we'd be willing to accept that. If you could update that issue it would be greatly appreciated.
